-- --------------------------------------------------------
-- Host:                         208.109.49.234
-- Server version:               10.6.21-MariaDB-cll-lve - MariaDB Server
-- Server OS:                    Linux
-- HeidiSQL Version:             12.5.0.6677
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping data for table SUBR.station_templates: ~1,098 rows (approximately)
INSERT INTO `station_templates` (`template_id`, `station_type`, `material_name`, `material_required`) VALUES
	(1, 'Orbital - Starport - Coriolis', 'Liquid Oxygen', 3781),
	(2, 'Orbital - Starport - Asteroid Base', 'Liquid Oxygen', 3781),
	(3, 'Orbital - Starport - Ocellus', 'Liquid Oxygen', 15124),
	(4, 'Orbital - Starport - Orbis', 'Liquid Oxygen', 15124),
	(5, 'Orbital - Outpost - Commercial', 'Liquid Oxygen', 1553),
	(6, 'Orbital - Outpost - Industrial', 'Liquid Oxygen', 1553),
	(7, 'Orbital - Outpost - Criminal', 'Liquid Oxygen', 1553),
	(8, 'Orbital - Outpost - Civilian', 'Liquid Oxygen', 1553),
	(9, 'Orbital - Outpost - Scientific', 'Liquid Oxygen', 1553),
	(10, 'Orbital - Outpost - Military', 'Liquid Oxygen', 1553),
	(11, 'Orbital - Installation - Satellite', 'Liquid Oxygen', 678),
	(12, 'Orbital - Installation - Comm Station', 'Liquid Oxygen', 678),
	(13, 'Orbital - Installation - Space Farm', 'Liquid Oxygen', 1071),
	(14, 'Orbital - Installation - Pirate Base', 'Liquid Oxygen', 911),
	(15, 'Orbital - Installation - Mining Outpost', 'Liquid Oxygen', 1028),
	(16, 'Orbital - Installation - Relay Station', 'Liquid Oxygen', 780),
	(17, 'Orbital - Installation - Military', 'Liquid Oxygen', 1424),
	(18, 'Orbital - Installation - Security Station', 'Liquid Oxygen', 1458),
	(19, 'Orbital - Installation - Government', 'Liquid Oxygen', 1479),
	(20, 'Orbital - Installation - Medical', 'Liquid Oxygen', 1727),
	(21, 'Orbital - Installation - Research Station', 'Liquid Oxygen', 1506),
	(22, 'Orbital - Installation - Tourist', 'Liquid Oxygen', 1813),
	(23, 'Orbital - Installation - Space Bar', 'Liquid Oxygen', 1738),
	(24, 'Surface - Planetary Port - Outpost Civilian', 'Liquid Oxygen', 2372),
	(25, 'Surface - Planetary Port - Outpost Industrial', 'Liquid Oxygen', 2372),
	(26, 'Surface - Planetary Port - Outpost Scientific', 'Liquid Oxygen', 2372),
	(27, 'Surface - Planetary Port - Port', 'Liquid Oxygen', 14232),
	(28, 'Surface - Settlement - Agriculture T1 S', 'Liquid Oxygen', 224),
	(29, 'Surface - Settlement - Agriculture T1 M', 'Liquid Oxygen', 448),
	(30, 'Surface - Settlement - Agriculture T2 L', 'Liquid Oxygen', 672),
	(31, 'Surface - Settlement - Extraction T1 S', 'Liquid Oxygen', 177),
	(32, 'Surface - Settlement - Extraction T1 M', 'Liquid Oxygen', 354),
	(33, 'Surface - Settlement - Extraction T2 L', 'Liquid Oxygen', 531),
	(34, 'Surface - Settlement - Industrial T1 S', 'Liquid Oxygen', 272),
	(35, 'Surface - Settlement - Industrial T1 M', 'Liquid Oxygen', 544),
	(36, 'Surface - Settlement - Industrial T2 L', 'Liquid Oxygen', 816),
	(37, 'Surface - Settlement - Military T1 S', 'Liquid Oxygen', 172),
	(38, 'Surface - Settlement - Military T1 M', 'Liquid Oxygen', 344),
	(39, 'Surface - Settlement - Military T2 L', 'Liquid Oxygen', 516),
	(40, 'Surface - Settlement - Research Bio T1 S', 'Liquid Oxygen', 351),
	(41, 'Surface - Settlement - Research Bio T1 M', 'Liquid Oxygen', 702),
	(42, 'Surface - Settlement - Research Bio T2 L', 'Liquid Oxygen', 1053),
	(43, 'Surface - Settlement - Tourism T1 S', 'Liquid Oxygen', 227),
	(44, 'Surface - Settlement - Tourism T1 M', 'Liquid Oxygen', 454),
	(45, 'Surface - Settlement - Tourism T2 L', 'Liquid Oxygen', 681),
	(46, 'Orbital - Installation - Space Farm', 'Pesticides', 123),
	(47, 'Surface - Settlement - Agriculture T1 S', 'Pesticides', 126),
	(48, 'Surface - Settlement - Agriculture T1 M', 'Pesticides', 252),
	(49, 'Surface - Settlement - Agriculture T2 L', 'Pesticides', 378),
	(50, 'Surface - Hub - Civilian', 'Pesticides', 378),
	(51, 'Surface - Planetary Port - Outpost Civilian', 'Surface Stabilisers', 610),
	(52, 'Surface - Planetary Port - Outpost Industrial', 'Surface Stabilisers', 610),
	(53, 'Surface - Planetary Port - Outpost Scientific', 'Surface Stabilisers', 610),
	(54, 'Surface - Planetary Port - Port', 'Surface Stabilisers', 3660),
	(55, 'Surface - Settlement - Agriculture T1 S', 'Surface Stabilisers', 56),
	(56, 'Surface - Settlement - Agriculture T1 M', 'Surface Stabilisers', 112),
	(57, 'Surface - Settlement - Agriculture T2 L', 'Surface Stabilisers', 168),
	(58, 'Surface - Settlement - Extraction T1 S', 'Surface Stabilisers', 89),
	(59, 'Surface - Settlement - Extraction T1 M', 'Surface Stabilisers', 178),
	(60, 'Surface - Settlement - Extraction T2 L', 'Surface Stabilisers', 267),
	(61, 'Surface - Settlement - Industrial T1 S', 'Surface Stabilisers', 68),
	(62, 'Surface - Settlement - Industrial T1 M', 'Surface Stabilisers', 136),
	(63, 'Surface - Settlement - Industrial T2 L', 'Surface Stabilisers', 204),
	(64, 'Surface - Settlement - Military T1 S', 'Surface Stabilisers', 60),
	(65, 'Surface - Settlement - Military T1 M', 'Surface Stabilisers', 120),
	(66, 'Surface - Settlement - Military T2 L', 'Surface Stabilisers', 180),
	(67, 'Surface - Settlement - Research Bio T1 S', 'Surface Stabilisers', 81),
	(68, 'Surface - Settlement - Research Bio T1 M', 'Surface Stabilisers', 162),
	(69, 'Surface - Settlement - Research Bio T2 L', 'Surface Stabilisers', 243),
	(70, 'Surface - Settlement - Tourism T1 S', 'Surface Stabilisers', 57),
	(71, 'Surface - Settlement - Tourism T1 M', 'Surface Stabilisers', 114),
	(72, 'Surface - Settlement - Tourism T2 L', 'Surface Stabilisers', 171),
	(73, 'Surface - Hub - Extraction', 'Surface Stabilisers', 756),
	(74, 'Surface - Hub - Civilian', 'Surface Stabilisers', 588),
	(75, 'Surface - Hub - Exploration', 'Surface Stabilisers', 1419),
	(76, 'Surface - Hub - Outpost', 'Surface Stabilisers', 1061),
	(77, 'Surface - Hub - Scientific', 'Surface Stabilisers', 534),
	(78, 'Surface - Hub - Military', 'Surface Stabilisers', 583),
	(79, 'Surface - Hub - Refinery', 'Surface Stabilisers', 558),
	(80, 'Surface - Hub - High Tech', 'Surface Stabilisers', 539),
	(81, 'Surface - Hub - Industrial', 'Surface Stabilisers', 498),
	(82, 'Orbital - Starport - Coriolis', 'Water', 1609),
	(83, 'Orbital - Starport - Asteroid Base', 'Water', 1609),
	(84, 'Orbital - Starport - Ocellus', 'Water', 6436),
	(85, 'Orbital - Starport - Orbis', 'Water', 6436),
	(86, 'Orbital - Outpost - Commercial', 'Water', 621),
	(87, 'Orbital - Outpost - Industrial', 'Water', 621),
	(88, 'Orbital - Outpost - Criminal', 'Water', 621),
	(89, 'Orbital - Outpost - Civilian', 'Water', 621),
	(90, 'Orbital - Outpost - Scientific', 'Water', 621),
	(91, 'Orbital - Outpost - Military', 'Water', 621),
	(92, 'Orbital - Installation - Satellite', 'Water', 22),
	(93, 'Orbital - Installation - Comm Station', 'Water', 22),
	(94, 'Orbital - Installation - Space Farm', 'Water', 173),
	(95, 'Orbital - Installation - Pirate Base', 'Water', 65),
	(96, 'Orbital - Installation - Mining Outpost', 'Water', 73),
	(97, 'Orbital - Installation - Relay Station', 'Water', 25),
	(98, 'Orbital - Installation - Military', 'Water', 238),
	(99, 'Orbital - Installation - Security Station', 'Water', 31),
	(100, 'Orbital - Installation - Government', 'Water', 154),
	(101, 'Orbital - Installation - Medical', 'Water', 278),
	(102, 'Orbital - Installation - Research Station', 'Water', 157),
	(103, 'Orbital - Installation - Tourist', 'Water', 324),
	(104, 'Orbital - Installation - Space Bar', 'Water', 311),
	(105, 'Surface - Planetary Port - Outpost Civilian', 'Evacuation Shelter', 204),
	(106, 'Surface - Planetary Port - Outpost Industrial', 'Evacuation Shelter', 204),
	(107, 'Surface - Planetary Port - Outpost Scientific', 'Evacuation Shelter', 204),
	(108, 'Surface - Planetary Port - Port', 'Evacuation Shelter', 816),
	(109, 'Surface - Settlement - Agriculture T1 S', 'Evacuation Shelter', 14),
	(110, 'Surface - Settlement - Agriculture T1 M', 'Evacuation Shelter', 28),
	(111, 'Surface - Settlement - Agriculture T2 L', 'Evacuation Shelter', 42),
	(112, 'Surface - Settlement - Extraction T1 S', 'Evacuation Shelter', 30),
	(113, 'Surface - Settlement - Extraction T1 M', 'Evacuation Shelter', 60),
	(114, 'Surface - Settlement - Extraction T2 L', 'Evacuation Shelter', 90),
	(115, 'Surface - Settlement - Industrial T1 S', 'Evacuation Shelter', 21),
	(116, 'Surface - Settlement - Industrial T1 M', 'Evacuation Shelter', 42),
	(117, 'Surface - Settlement - Industrial T2 L', 'Evacuation Shelter', 63),
	(118, 'Surface - Settlement - Military T1 S', 'Evacuation Shelter', 36),
	(119, 'Surface - Settlement - Military T1 M', 'Evacuation Shelter', 72),
	(120, 'Surface - Settlement - Military T2 L', 'Evacuation Shelter', 108),
	(121, 'Surface - Settlement - Research Bio T1 S', 'Evacuation Shelter', 27),
	(122, 'Surface - Settlement - Research Bio T1 M', 'Evacuation Shelter', 54),
	(123, 'Surface - Settlement - Research Bio T2 L', 'Evacuation Shelter', 81),
	(124, 'Surface - Settlement - Tourism T1 S', 'Evacuation Shelter', 22),
	(125, 'Surface - Settlement - Tourism T1 M', 'Evacuation Shelter', 44),
	(126, 'Surface - Settlement - Tourism T2 L', 'Evacuation Shelter', 66),
	(127, 'Surface - Hub - Extraction', 'Evacuation Shelter', 51),
	(128, 'Surface - Hub - Civilian', 'Evacuation Shelter', 68),
	(129, 'Surface - Hub - Exploration', 'Evacuation Shelter', 36),
	(130, 'Surface - Hub - Outpost', 'Evacuation Shelter', 49),
	(131, 'Surface - Hub - Scientific', 'Evacuation Shelter', 36),
	(132, 'Surface - Hub - Military', 'Evacuation Shelter', 75),
	(133, 'Surface - Hub - Refinery', 'Evacuation Shelter', 56),
	(134, 'Surface - Hub - High Tech', 'Evacuation Shelter', 45),
	(135, 'Surface - Hub - Industrial', 'Evacuation Shelter', 50),
	(136, 'Surface - Planetary Port - Outpost Civilian', 'Survival Equipment', 55),
	(137, 'Surface - Planetary Port - Outpost Industrial', 'Survival Equipment', 55),
	(138, 'Surface - Planetary Port - Outpost Scientific', 'Survival Equipment', 55),
	(139, 'Surface - Planetary Port - Port', 'Survival Equipment', 220),
	(140, 'Surface - Settlement - Agriculture T1 S', 'Survival Equipment', 14),
	(141, 'Surface - Settlement - Agriculture T1 M', 'Survival Equipment', 28),
	(142, 'Surface - Settlement - Agriculture T2 L', 'Survival Equipment', 42),
	(143, 'Surface - Settlement - Extraction T1 S', 'Survival Equipment', 15),
	(144, 'Surface - Settlement - Extraction T1 M', 'Survival Equipment', 30),
	(145, 'Surface - Settlement - Extraction T2 L', 'Survival Equipment', 45),
	(146, 'Surface - Settlement - Industrial T1 S', 'Survival Equipment', 14),
	(147, 'Surface - Settlement - Industrial T1 M', 'Survival Equipment', 28),
	(148, 'Surface - Settlement - Industrial T2 L', 'Survival Equipment', 42),
	(149, 'Surface - Settlement - Military T1 S', 'Survival Equipment', 24),
	(150, 'Surface - Settlement - Military T1 M', 'Survival Equipment', 48),
	(151, 'Surface - Settlement - Military T2 L', 'Survival Equipment', 72),
	(152, 'Surface - Settlement - Research Bio T1 S', 'Survival Equipment', 14),
	(153, 'Surface - Settlement - Research Bio T1 M', 'Survival Equipment', 28),
	(154, 'Surface - Settlement - Research Bio T2 L', 'Survival Equipment', 42),
	(155, 'Surface - Settlement - Tourism T1 S', 'Survival Equipment', 15),
	(156, 'Surface - Settlement - Tourism T1 M', 'Survival Equipment', 30),
	(157, 'Surface - Settlement - Tourism T2 L', 'Survival Equipment', 45),
	(158, 'Surface - Hub - Extraction', 'Survival Equipment', 26),
	(159, 'Surface - Hub - Civilian', 'Survival Equipment', 38),
	(160, 'Surface - Hub - Exploration', 'Survival Equipment', 18),
	(161, 'Surface - Hub - Outpost', 'Survival Equipment', 29),
	(162, 'Surface - Hub - Scientific', 'Survival Equipment', 27),
	(163, 'Surface - Hub - Military', 'Survival Equipment', 50),
	(164, 'Surface - Hub - Refinery', 'Survival Equipment', 28),
	(165, 'Surface - Hub - High Tech', 'Survival Equipment', 27),
	(166, 'Surface - Hub - Industrial', 'Survival Equipment', 25),
	(167, 'Orbital - Installation - Pirate Base', 'Beer', 380),
	(168, 'Orbital - Installation - Tourist', 'Beer', 389),
	(169, 'Orbital - Installation - Space Bar', 'Beer', 497),
	(170, 'Surface - Settlement - Tourism T1 S', 'Beer', 311),
	(171, 'Surface - Settlement - Tourism T1 M', 'Beer', 622),
	(172, 'Surface - Settlement - Tourism T2 L', 'Beer', 933),
	(173, 'Orbital - Installation - Pirate Base', 'Liquor', 228),
	(174, 'Orbital - Installation - Tourist', 'Liquor', 195),
	(175, 'Orbital - Installation - Space Bar', 'Liquor', 311),
	(176, 'Surface - Settlement - Tourism T1 S', 'Liquor', 128),
	(177, 'Surface - Settlement - Tourism T1 M', 'Liquor', 256),
	(178, 'Surface - Settlement - Tourism T2 L', 'Liquor', 384),
	(179, 'Orbital - Installation - Tourist', 'Wine', 259),
	(180, 'Orbital - Installation - Space Bar', 'Wine', 621),
	(181, 'Surface - Settlement - Tourism T1 S', 'Wine', 156),
	(182, 'Surface - Settlement - Tourism T1 M', 'Wine', 312),
	(183, 'Surface - Settlement - Tourism T2 L', 'Wine', 468),
	(184, 'Orbital - Installation - Tourist', 'Animal Meat', 78),
	(185, 'Orbital - Installation - Space Bar', 'Animal Meat', 38),
	(186, 'Surface - Settlement - Tourism T1 S', 'Animal Meat', 71),
	(187, 'Surface - Settlement - Tourism T1 M', 'Animal Meat', 142),
	(188, 'Surface - Settlement - Tourism T2 L', 'Animal Meat', 213),
	(189, 'Orbital - Installation - Tourist', 'Coffee', 130),
	(190, 'Orbital - Installation - Space Bar', 'Coffee', 63),
	(191, 'Surface - Settlement - Tourism T1 S', 'Coffee', 71),
	(192, 'Surface - Settlement - Tourism T1 M', 'Coffee', 142),
	(193, 'Surface - Settlement - Tourism T2 L', 'Coffee', 213),
	(194, 'Orbital - Installation - Tourist', 'Fish', 39),
	(195, 'Orbital - Installation - Space Bar', 'Fish', 19),
	(196, 'Surface - Settlement - Tourism T1 S', 'Fish', 36),
	(197, 'Surface - Settlement - Tourism T1 M', 'Fish', 72),
	(198, 'Surface - Settlement - Tourism T2 L', 'Fish', 108),
	(199, 'Orbital - Starport - Coriolis', 'Food Cartridges', 242),
	(200, 'Orbital - Starport - Asteroid Base', 'Food Cartridges', 242),
	(201, 'Orbital - Starport - Ocellus', 'Food Cartridges', 484),
	(202, 'Orbital - Starport - Orbis', 'Food Cartridges', 484),
	(203, 'Orbital - Outpost - Commercial', 'Food Cartridges', 94),
	(204, 'Orbital - Outpost - Industrial', 'Food Cartridges', 94),
	(205, 'Orbital - Outpost - Criminal', 'Food Cartridges', 94),
	(206, 'Orbital - Outpost - Civilian', 'Food Cartridges', 94),
	(207, 'Orbital - Outpost - Scientific', 'Food Cartridges', 94),
	(208, 'Orbital - Outpost - Military', 'Food Cartridges', 94),
	(209, 'Orbital - Installation - Satellite', 'Food Cartridges', 26),
	(210, 'Orbital - Installation - Comm Station', 'Food Cartridges', 26),
	(211, 'Orbital - Installation - Space Farm', 'Food Cartridges', 46),
	(212, 'Orbital - Installation - Pirate Base', 'Food Cartridges', 61),
	(213, 'Orbital - Installation - Mining Outpost', 'Food Cartridges', 52),
	(214, 'Orbital - Installation - Relay Station', 'Food Cartridges', 30),
	(215, 'Orbital - Installation - Military', 'Food Cartridges', 107),
	(216, 'Orbital - Installation - Security Station', 'Food Cartridges', 37),
	(217, 'Orbital - Installation - Government', 'Food Cartridges', 93),
	(218, 'Orbital - Installation - Medical', 'Food Cartridges', 75),
	(219, 'Orbital - Installation - Research Station', 'Food Cartridges', 76),
	(220, 'Surface - Planetary Port - Outpost Civilian', 'Food Cartridges', 136),
	(221, 'Surface - Planetary Port - Outpost Industrial', 'Food Cartridges', 136),
	(222, 'Surface - Planetary Port - Outpost Scientific', 'Food Cartridges', 136),
	(223, 'Surface - Planetary Port - Port', 'Food Cartridges', 544),
	(224, 'Surface - Settlement - Agriculture T1 S', 'Food Cartridges', 42),
	(225, 'Surface - Settlement - Agriculture T1 M', 'Food Cartridges', 84),
	(226, 'Surface - Settlement - Agriculture T2 L', 'Food Cartridges', 126),
	(227, 'Surface - Settlement - Extraction T1 S', 'Food Cartridges', 45),
	(228, 'Surface - Settlement - Extraction T1 M', 'Food Cartridges', 90),
	(229, 'Surface - Settlement - Extraction T2 L', 'Food Cartridges', 135),
	(230, 'Surface - Settlement - Industrial T1 S', 'Food Cartridges', 41),
	(231, 'Surface - Settlement - Industrial T1 M', 'Food Cartridges', 82),
	(232, 'Surface - Settlement - Industrial T2 L', 'Food Cartridges', 123),
	(233, 'Surface - Settlement - Military T1 S', 'Food Cartridges', 36),
	(234, 'Surface - Settlement - Military T1 M', 'Food Cartridges', 72),
	(235, 'Surface - Settlement - Military T2 L', 'Food Cartridges', 108),
	(236, 'Surface - Settlement - Research Bio T1 S', 'Food Cartridges', 41),
	(237, 'Surface - Settlement - Research Bio T1 M', 'Food Cartridges', 82),
	(238, 'Surface - Settlement - Research Bio T2 L', 'Food Cartridges', 123),
	(239, 'Surface - Hub - Extraction', 'Food Cartridges', 51),
	(240, 'Surface - Hub - Civilian', 'Food Cartridges', 68),
	(241, 'Surface - Hub - Exploration', 'Food Cartridges', 54),
	(242, 'Surface - Hub - Outpost', 'Food Cartridges', 174),
	(243, 'Surface - Hub - Scientific', 'Food Cartridges', 54),
	(244, 'Surface - Hub - Military', 'Food Cartridges', 125),
	(245, 'Surface - Hub - Refinery', 'Food Cartridges', 56),
	(246, 'Surface - Hub - High Tech', 'Food Cartridges', 54),
	(247, 'Surface - Hub - Industrial', 'Food Cartridges', 50),
	(248, 'Orbital - Starport - Coriolis', 'Fruit and Vegetables', 145),
	(249, 'Orbital - Starport - Asteroid Base', 'Fruit and Vegetables', 145),
	(250, 'Orbital - Starport - Ocellus', 'Fruit and Vegetables', 290),
	(251, 'Orbital - Starport - Orbis', 'Fruit and Vegetables', 290),
	(252, 'Orbital - Outpost - Commercial', 'Fruit and Vegetables', 50),
	(253, 'Orbital - Outpost - Industrial', 'Fruit and Vegetables', 50),
	(254, 'Orbital - Outpost - Criminal', 'Fruit and Vegetables', 50),
	(255, 'Orbital - Outpost - Civilian', 'Fruit and Vegetables', 50),
	(256, 'Orbital - Outpost - Scientific', 'Fruit and Vegetables', 50),
	(257, 'Orbital - Outpost - Military', 'Fruit and Vegetables', 50),
	(258, 'Orbital - Installation - Satellite', 'Fruit and Vegetables', 9),
	(259, 'Orbital - Installation - Comm Station', 'Fruit and Vegetables', 9),
	(260, 'Orbital - Installation - Space Farm', 'Fruit and Vegetables', 69),
	(261, 'Orbital - Installation - Pirate Base', 'Fruit and Vegetables', 16),
	(262, 'Orbital - Installation - Mining Outpost', 'Fruit and Vegetables', 18),
	(263, 'Orbital - Installation - Relay Station', 'Fruit and Vegetables', 10),
	(264, 'Orbital - Installation - Military', 'Fruit and Vegetables', 48),
	(265, 'Orbital - Installation - Security Station', 'Fruit and Vegetables', 13),
	(266, 'Orbital - Installation - Government', 'Fruit and Vegetables', 37),
	(267, 'Orbital - Installation - Medical', 'Fruit and Vegetables', 50),
	(268, 'Orbital - Installation - Research Station', 'Fruit and Vegetables', 26),
	(269, 'Orbital - Installation - Tourist', 'Fruit and Vegetables', 65),
	(270, 'Orbital - Installation - Space Bar', 'Fruit and Vegetables', 38),
	(271, 'Surface - Planetary Port - Outpost Civilian', 'Fruit and Vegetables', 95),
	(272, 'Surface - Planetary Port - Outpost Industrial', 'Fruit and Vegetables', 95),
	(273, 'Surface - Planetary Port - Outpost Scientific', 'Fruit and Vegetables', 95),
	(274, 'Surface - Planetary Port - Port', 'Fruit and Vegetables', 380),
	(275, 'Surface - Settlement - Agriculture T1 S', 'Fruit and Vegetables', 63),
	(276, 'Surface - Settlement - Agriculture T1 M', 'Fruit and Vegetables', 126),
	(277, 'Surface - Settlement - Agriculture T2 L', 'Fruit and Vegetables', 189),
	(278, 'Surface - Settlement - Extraction T1 S', 'Fruit and Vegetables', 30),
	(279, 'Surface - Settlement - Extraction T1 M', 'Fruit and Vegetables', 60),
	(280, 'Surface - Settlement - Extraction T2 L', 'Fruit and Vegetables', 90),
	(281, 'Surface - Settlement - Industrial T1 S', 'Fruit and Vegetables', 28),
	(282, 'Surface - Settlement - Industrial T1 M', 'Fruit and Vegetables', 56),
	(283, 'Surface - Settlement - Industrial T2 L', 'Fruit and Vegetables', 84),
	(284, 'Surface - Settlement - Military T1 S', 'Fruit and Vegetables', 24),
	(285, 'Surface - Settlement - Military T1 M', 'Fruit and Vegetables', 48),
	(286, 'Surface - Settlement - Military T2 L', 'Fruit and Vegetables', 72),
	(287, 'Surface - Settlement - Research Bio T1 S', 'Fruit and Vegetables', 27),
	(288, 'Surface - Settlement - Research Bio T1 M', 'Fruit and Vegetables', 54),
	(289, 'Surface - Settlement - Research Bio T2 L', 'Fruit and Vegetables', 81),
	(290, 'Surface - Settlement - Tourism T1 S', 'Fruit and Vegetables', 71),
	(291, 'Surface - Settlement - Tourism T1 M', 'Fruit and Vegetables', 142),
	(292, 'Surface - Settlement - Tourism T2 L', 'Fruit and Vegetables', 213),
	(293, 'Surface - Hub - Extraction', 'Fruit and Vegetables', 34),
	(294, 'Surface - Hub - Civilian', 'Fruit and Vegetables', 42),
	(295, 'Surface - Hub - Exploration', 'Fruit and Vegetables', 36),
	(296, 'Surface - Hub - Outpost', 'Fruit and Vegetables', 87),
	(297, 'Surface - Hub - Scientific', 'Fruit and Vegetables', 36),
	(298, 'Surface - Hub - Military', 'Fruit and Vegetables', 42),
	(299, 'Surface - Hub - Refinery', 'Fruit and Vegetables', 38),
	(300, 'Surface - Hub - High Tech', 'Fruit and Vegetables', 36),
	(301, 'Surface - Hub - Industrial', 'Fruit and Vegetables', 34),
	(302, 'Orbital - Installation - Space Farm', 'Grain', 92),
	(303, 'Surface - Settlement - Agriculture T1 S', 'Grain', 77),
	(304, 'Surface - Settlement - Agriculture T1 M', 'Grain', 154),
	(305, 'Surface - Settlement - Agriculture T2 L', 'Grain', 231),
	(306, 'Orbital - Installation - Tourist', 'Tea', 259),
	(307, 'Orbital - Installation - Space Bar', 'Tea', 178),
	(308, 'Surface - Settlement - Tourism T1 S', 'Tea', 170),
	(309, 'Surface - Settlement - Tourism T1 M', 'Tea', 340),
	(310, 'Surface - Settlement - Tourism T2 L', 'Tea', 510),
	(311, 'Orbital - Starport - Coriolis', 'Ceramic Composites', 1207),
	(312, 'Orbital - Starport - Asteroid Base', 'Ceramic Composites', 1207),
	(313, 'Orbital - Starport - Ocellus', 'Ceramic Composites', 4828),
	(314, 'Orbital - Starport - Orbis', 'Ceramic Composites', 4828),
	(315, 'Orbital - Outpost - Commercial', 'Ceramic Composites', 497),
	(316, 'Orbital - Outpost - Industrial', 'Ceramic Composites', 497),
	(317, 'Orbital - Outpost - Criminal', 'Ceramic Composites', 497),
	(318, 'Orbital - Outpost - Civilian', 'Ceramic Composites', 497),
	(319, 'Orbital - Outpost - Scientific', 'Ceramic Composites', 497),
	(320, 'Orbital - Outpost - Military', 'Ceramic Composites', 497),
	(321, 'Orbital - Installation - Satellite', 'Ceramic Composites', 85),
	(322, 'Orbital - Installation - Comm Station', 'Ceramic Composites', 85),
	(323, 'Orbital - Installation - Space Farm', 'Ceramic Composites', 77),
	(324, 'Orbital - Installation - Pirate Base', 'Ceramic Composites', 95),
	(325, 'Orbital - Installation - Mining Outpost', 'Ceramic Composites', 86),
	(326, 'Orbital - Installation - Relay Station', 'Ceramic Composites', 98),
	(327, 'Orbital - Installation - Military', 'Ceramic Composites', 238),
	(328, 'Orbital - Installation - Security Station', 'Ceramic Composites', 122),
	(329, 'Orbital - Installation - Government', 'Ceramic Composites', 154),
	(330, 'Orbital - Installation - Medical', 'Ceramic Composites', 155),
	(331, 'Orbital - Installation - Research Station', 'Ceramic Composites', 157),
	(332, 'Orbital - Installation - Tourist', 'Ceramic Composites', 130),
	(333, 'Orbital - Installation - Space Bar', 'Ceramic Composites', 125),
	(334, 'Surface - Planetary Port - Outpost Civilian', 'Ceramic Composites', 814),
	(335, 'Surface - Planetary Port - Outpost Industrial', 'Ceramic Composites', 814),
	(336, 'Surface - Planetary Port - Outpost Scientific', 'Ceramic Composites', 814),
	(337, 'Surface - Planetary Port - Port', 'Ceramic Composites', 4884),
	(338, 'Surface - Settlement - Agriculture T1 S', 'Ceramic Composites', 28),
	(339, 'Surface - Settlement - Agriculture T1 M', 'Ceramic Composites', 56),
	(340, 'Surface - Settlement - Agriculture T2 L', 'Ceramic Composites', 84),
	(341, 'Surface - Settlement - Extraction T1 S', 'Ceramic Composites', 59),
	(342, 'Surface - Settlement - Extraction T1 M', 'Ceramic Composites', 118),
	(343, 'Surface - Settlement - Extraction T2 L', 'Ceramic Composites', 177),
	(344, 'Surface - Settlement - Industrial T1 S', 'Ceramic Composites', 55),
	(345, 'Surface - Settlement - Industrial T1 M', 'Ceramic Composites', 110),
	(346, 'Surface - Settlement - Industrial T2 L', 'Ceramic Composites', 165),
	(347, 'Surface - Settlement - Military T1 S', 'Ceramic Composites', 60),
	(348, 'Surface - Settlement - Military T1 M', 'Ceramic Composites', 120),
	(349, 'Surface - Settlement - Military T2 L', 'Ceramic Composites', 180),
	(350, 'Surface - Settlement - Research Bio T1 S', 'Ceramic Composites', 41),
	(351, 'Surface - Settlement - Research Bio T1 M', 'Ceramic Composites', 82),
	(352, 'Surface - Settlement - Research Bio T2 L', 'Ceramic Composites', 123),
	(353, 'Surface - Settlement - Tourism T1 S', 'Ceramic Composites', 43),
	(354, 'Surface - Settlement - Tourism T1 M', 'Ceramic Composites', 86),
	(355, 'Surface - Settlement - Tourism T2 L', 'Ceramic Composites', 129),
	(356, 'Surface - Hub - Extraction', 'Ceramic Composites', 252),
	(357, 'Surface - Hub - Civilian', 'Ceramic Composites', 126),
	(358, 'Surface - Hub - Exploration', 'Ceramic Composites', 134),
	(359, 'Surface - Hub - Outpost', 'Ceramic Composites', 145),
	(360, 'Surface - Hub - Scientific', 'Ceramic Composites', 223),
	(361, 'Surface - Hub - Military', 'Ceramic Composites', 375),
	(362, 'Surface - Hub - Refinery', 'Ceramic Composites', 279),
	(363, 'Surface - Hub - High Tech', 'Ceramic Composites', 225),
	(364, 'Surface - Hub - Industrial', 'Ceramic Composites', 249),
	(365, 'Orbital - Starport - Coriolis', 'CMM Composite', 11261),
	(366, 'Orbital - Starport - Asteroid Base', 'CMM Composite', 11261),
	(367, 'Orbital - Starport - Ocellus', 'CMM Composite', 45044),
	(368, 'Orbital - Starport - Orbis', 'CMM Composite', 45044),
	(369, 'Orbital - Outpost - Commercial', 'CMM Composite', 3912),
	(370, 'Orbital - Outpost - Industrial', 'CMM Composite', 3912),
	(371, 'Orbital - Outpost - Criminal', 'CMM Composite', 3912),
	(372, 'Orbital - Outpost - Civilian', 'CMM Composite', 3912),
	(373, 'Orbital - Outpost - Scientific', 'CMM Composite', 3912),
	(374, 'Orbital - Outpost - Military', 'CMM Composite', 3912),
	(375, 'Orbital - Installation - Military', 'CMM Composite', 356),
	(376, 'Surface - Planetary Port - Outpost Civilian', 'CMM Composite', 6776),
	(377, 'Surface - Planetary Port - Outpost Industrial', 'CMM Composite', 6776),
	(378, 'Surface - Planetary Port - Outpost Scientific', 'CMM Composite', 6776),
	(379, 'Surface - Planetary Port - Port', 'CMM Composite', 40656),
	(380, 'Surface - Settlement - Military T1 S', 'CMM Composite', 356),
	(381, 'Surface - Settlement - Military T1 M', 'CMM Composite', 712),
	(382, 'Surface - Settlement - Military T2 L', 'CMM Composite', 1068),
	(383, 'Surface - Hub - Military', 'CMM Composite', 333),
	(384, 'Surface - Hub - High Tech', 'CMM Composite', 270),
	(385, 'Orbital - Starport - Coriolis', 'Insulating Membrane', 644),
	(386, 'Orbital - Starport - Asteroid Base', 'Insulating Membrane', 644),
	(387, 'Orbital - Starport - Ocellus', 'Insulating Membrane', 1288),
	(388, 'Orbital - Starport - Orbis', 'Insulating Membrane', 1288),
	(389, 'Orbital - Outpost - Commercial', 'Insulating Membrane', 311),
	(390, 'Orbital - Outpost - Industrial', 'Insulating Membrane', 311),
	(391, 'Orbital - Outpost - Criminal', 'Insulating Membrane', 311),
	(392, 'Orbital - Outpost - Civilian', 'Insulating Membrane', 311),
	(393, 'Orbital - Outpost - Scientific', 'Insulating Membrane', 311),
	(394, 'Orbital - Outpost - Military', 'Insulating Membrane', 311),
	(395, 'Orbital - Installation - Satellite', 'Insulating Membrane', 106),
	(396, 'Orbital - Installation - Comm Station', 'Insulating Membrane', 106),
	(397, 'Orbital - Installation - Space Farm', 'Insulating Membrane', 192),
	(398, 'Orbital - Installation - Pirate Base', 'Insulating Membrane', 95),
	(399, 'Orbital - Installation - Mining Outpost', 'Insulating Membrane', 129),
	(400, 'Orbital - Installation - Relay Station', 'Insulating Membrane', 122),
	(401, 'Orbital - Installation - Military', 'Insulating Membrane', 178),
	(402, 'Orbital - Installation - Security Station', 'Insulating Membrane', 183),
	(403, 'Orbital - Installation - Government', 'Insulating Membrane', 247),
	(404, 'Orbital - Installation - Medical', 'Insulating Membrane', 309),
	(405, 'Orbital - Installation - Research Station', 'Insulating Membrane', 314),
	(406, 'Orbital - Installation - Tourist', 'Insulating Membrane', 259),
	(407, 'Orbital - Installation - Space Bar', 'Insulating Membrane', 249),
	(408, 'Orbital - Starport - Coriolis', 'Polymers', 1046),
	(409, 'Orbital - Starport - Asteroid Base', 'Polymers', 1046),
	(410, 'Orbital - Starport - Ocellus', 'Polymers', 2092),
	(411, 'Orbital - Starport - Orbis', 'Polymers', 2092),
	(412, 'Orbital - Outpost - Commercial', 'Polymers', 497),
	(413, 'Orbital - Outpost - Industrial', 'Polymers', 497),
	(414, 'Orbital - Outpost - Criminal', 'Polymers', 497),
	(415, 'Orbital - Outpost - Civilian', 'Polymers', 497),
	(416, 'Orbital - Outpost - Scientific', 'Polymers', 497),
	(417, 'Orbital - Outpost - Military', 'Polymers', 497),
	(418, 'Orbital - Installation - Satellite', 'Polymers', 170),
	(419, 'Orbital - Installation - Comm Station', 'Polymers', 170),
	(420, 'Orbital - Installation - Space Farm', 'Polymers', 230),
	(421, 'Orbital - Installation - Pirate Base', 'Polymers', 190),
	(422, 'Orbital - Installation - Mining Outpost', 'Polymers', 215),
	(423, 'Orbital - Installation - Relay Station', 'Polymers', 195),
	(424, 'Orbital - Installation - Military', 'Polymers', 416),
	(425, 'Orbital - Installation - Security Station', 'Polymers', 243),
	(426, 'Orbital - Installation - Government', 'Polymers', 370),
	(427, 'Orbital - Installation - Medical', 'Polymers', 371),
	(428, 'Orbital - Installation - Research Station', 'Polymers', 377),
	(429, 'Orbital - Installation - Tourist', 'Polymers', 324),
	(430, 'Orbital - Installation - Space Bar', 'Polymers', 311),
	(431, 'Surface - Planetary Port - Outpost Civilian', 'Polymers', 678),
	(432, 'Surface - Planetary Port - Outpost Industrial', 'Polymers', 678),
	(433, 'Surface - Planetary Port - Outpost Scientific', 'Polymers', 678),
	(434, 'Surface - Planetary Port - Port', 'Polymers', 2712),
	(435, 'Surface - Settlement - Agriculture T1 S', 'Polymers', 91),
	(436, 'Surface - Settlement - Agriculture T1 M', 'Polymers', 182),
	(437, 'Surface - Settlement - Agriculture T2 L', 'Polymers', 273),
	(438, 'Surface - Settlement - Extraction T1 S', 'Polymers', 118),
	(439, 'Surface - Settlement - Extraction T1 M', 'Polymers', 236),
	(440, 'Surface - Settlement - Extraction T2 L', 'Polymers', 354),
	(441, 'Surface - Settlement - Industrial T1 S', 'Polymers', 109),
	(442, 'Surface - Settlement - Industrial T1 M', 'Polymers', 218),
	(443, 'Surface - Settlement - Industrial T2 L', 'Polymers', 327),
	(444, 'Surface - Settlement - Military T1 S', 'Polymers', 119),
	(445, 'Surface - Settlement - Military T1 M', 'Polymers', 238),
	(446, 'Surface - Settlement - Military T2 L', 'Polymers', 357),
	(447, 'Surface - Settlement - Research Bio T1 S', 'Polymers', 115),
	(448, 'Surface - Settlement - Research Bio T1 M', 'Polymers', 230),
	(449, 'Surface - Settlement - Research Bio T2 L', 'Polymers', 345),
	(450, 'Surface - Settlement - Tourism T1 S', 'Polymers', 114),
	(451, 'Surface - Settlement - Tourism T1 M', 'Polymers', 228),
	(452, 'Surface - Settlement - Tourism T2 L', 'Polymers', 342),
	(453, 'Surface - Hub - Extraction', 'Polymers', 672),
	(454, 'Surface - Hub - Civilian', 'Polymers', 630),
	(455, 'Surface - Hub - Exploration', 'Polymers', 666),
	(456, 'Surface - Hub - Scientific', 'Polymers', 712),
	(457, 'Surface - Hub - Military', 'Polymers', 708),
	(458, 'Surface - Hub - Refinery', 'Polymers', 744),
	(459, 'Surface - Hub - High Tech', 'Polymers', 673),
	(460, 'Surface - Hub - Industrial', 'Polymers', 664),
	(461, 'Orbital - Starport - Coriolis', 'Semiconductors', 161),
	(462, 'Orbital - Starport - Asteroid Base', 'Semiconductors', 161),
	(463, 'Orbital - Starport - Ocellus', 'Semiconductors', 322),
	(464, 'Orbital - Starport - Orbis', 'Semiconductors', 322),
	(465, 'Orbital - Outpost - Commercial', 'Semiconductors', 56),
	(466, 'Orbital - Outpost - Industrial', 'Semiconductors', 56),
	(467, 'Orbital - Outpost - Criminal', 'Semiconductors', 56),
	(468, 'Orbital - Outpost - Civilian', 'Semiconductors', 56),
	(469, 'Orbital - Outpost - Scientific', 'Semiconductors', 56),
	(470, 'Orbital - Outpost - Military', 'Semiconductors', 56),
	(471, 'Orbital - Installation - Satellite', 'Semiconductors', 34),
	(472, 'Orbital - Installation - Comm Station', 'Semiconductors', 34),
	(473, 'Orbital - Installation - Relay Station', 'Semiconductors', 39),
	(474, 'Orbital - Installation - Research Station', 'Semiconductors', 51),
	(475, 'Surface - Planetary Port - Outpost Civilian', 'Semiconductors', 102),
	(476, 'Surface - Planetary Port - Outpost Industrial', 'Semiconductors', 102),
	(477, 'Surface - Planetary Port - Outpost Scientific', 'Semiconductors', 102),
	(478, 'Surface - Planetary Port - Port', 'Semiconductors', 408),
	(479, 'Surface - Settlement - Industrial T1 S', 'Semiconductors', 14),
	(480, 'Surface - Settlement - Industrial T1 M', 'Semiconductors', 28),
	(481, 'Surface - Settlement - Industrial T2 L', 'Semiconductors', 42),
	(482, 'Surface - Settlement - Research Bio T1 S', 'Semiconductors', 21),
	(483, 'Surface - Settlement - Research Bio T1 M', 'Semiconductors', 42),
	(484, 'Surface - Settlement - Research Bio T2 L', 'Semiconductors', 63),
	(485, 'Surface - Hub - Scientific', 'Semiconductors', 72),
	(486, 'Surface - Hub - High Tech', 'Semiconductors', 108),
	(487, 'Surface - Hub - Industrial', 'Semiconductors', 75),
	(488, 'Orbital - Starport - Coriolis', 'Superconductors', 282),
	(489, 'Orbital - Starport - Asteroid Base', 'Superconductors', 282),
	(490, 'Orbital - Starport - Ocellus', 'Superconductors', 564),
	(491, 'Orbital - Starport - Orbis', 'Superconductors', 564),
	(492, 'Orbital - Outpost - Commercial', 'Superconductors', 100),
	(493, 'Orbital - Outpost - Industrial', 'Superconductors', 100),
	(494, 'Orbital - Outpost - Criminal', 'Superconductors', 100),
	(495, 'Orbital - Outpost - Civilian', 'Superconductors', 100),
	(496, 'Orbital - Outpost - Scientific', 'Superconductors', 100),
	(497, 'Orbital - Outpost - Military', 'Superconductors', 100),
	(498, 'Orbital - Installation - Satellite', 'Superconductors', 60),
	(499, 'Orbital - Installation - Comm Station', 'Superconductors', 60),
	(500, 'Orbital - Installation - Relay Station', 'Superconductors', 59),
	(501, 'Orbital - Installation - Research Station', 'Superconductors', 88),
	(502, 'Surface - Planetary Port - Outpost Civilian', 'Superconductors', 136),
	(503, 'Surface - Planetary Port - Outpost Industrial', 'Superconductors', 136),
	(504, 'Surface - Planetary Port - Outpost Scientific', 'Superconductors', 136),
	(505, 'Surface - Planetary Port - Port', 'Superconductors', 544),
	(506, 'Surface - Settlement - Industrial T1 S', 'Superconductors', 14),
	(507, 'Surface - Settlement - Industrial T1 M', 'Superconductors', 28),
	(508, 'Surface - Settlement - Industrial T2 L', 'Superconductors', 42),
	(509, 'Surface - Settlement - Research Bio T1 S', 'Superconductors', 21),
	(510, 'Surface - Settlement - Research Bio T1 M', 'Superconductors', 42),
	(511, 'Surface - Settlement - Research Bio T2 L', 'Superconductors', 63),
	(512, 'Surface - Hub - Scientific', 'Superconductors', 72),
	(513, 'Surface - Hub - High Tech', 'Superconductors', 108),
	(514, 'Surface - Hub - Industrial', 'Superconductors', 75),
	(515, 'Surface - Planetary Port - Outpost Civilian', 'Building Fabricators', 407),
	(516, 'Surface - Planetary Port - Outpost Industrial', 'Building Fabricators', 407),
	(517, 'Surface - Planetary Port - Outpost Scientific', 'Building Fabricators', 407),
	(518, 'Surface - Planetary Port - Port', 'Building Fabricators', 2442),
	(519, 'Surface - Settlement - Agriculture T1 S', 'Building Fabricators', 42),
	(520, 'Surface - Settlement - Agriculture T1 M', 'Building Fabricators', 84),
	(521, 'Surface - Settlement - Agriculture T2 L', 'Building Fabricators', 126),
	(522, 'Surface - Settlement - Extraction T1 S', 'Building Fabricators', 59),
	(523, 'Surface - Settlement - Extraction T1 M', 'Building Fabricators', 118),
	(524, 'Surface - Settlement - Extraction T2 L', 'Building Fabricators', 177),
	(525, 'Surface - Settlement - Industrial T1 S', 'Building Fabricators', 55),
	(526, 'Surface - Settlement - Industrial T1 M', 'Building Fabricators', 110),
	(527, 'Surface - Settlement - Industrial T2 L', 'Building Fabricators', 165),
	(528, 'Surface - Settlement - Military T1 S', 'Building Fabricators', 60),
	(529, 'Surface - Settlement - Military T1 M', 'Building Fabricators', 120),
	(530, 'Surface - Settlement - Military T2 L', 'Building Fabricators', 180),
	(531, 'Surface - Settlement - Research Bio T1 S', 'Building Fabricators', 54),
	(532, 'Surface - Settlement - Research Bio T1 M', 'Building Fabricators', 108),
	(533, 'Surface - Settlement - Research Bio T2 L', 'Building Fabricators', 162),
	(534, 'Surface - Settlement - Tourism T1 S', 'Building Fabricators', 29),
	(535, 'Surface - Settlement - Tourism T1 M', 'Building Fabricators', 58),
	(536, 'Surface - Settlement - Tourism T2 L', 'Building Fabricators', 87),
	(537, 'Surface - Hub - Extraction', 'Building Fabricators', 210),
	(538, 'Surface - Hub - Civilian', 'Building Fabricators', 84),
	(539, 'Surface - Hub - Exploration', 'Building Fabricators', 89),
	(540, 'Surface - Hub - Outpost', 'Building Fabricators', 290),
	(541, 'Surface - Hub - Scientific', 'Building Fabricators', 178),
	(542, 'Surface - Hub - Military', 'Building Fabricators', 333),
	(543, 'Surface - Hub - Refinery', 'Building Fabricators', 233),
	(544, 'Surface - Hub - High Tech', 'Building Fabricators', 135),
	(545, 'Surface - Hub - Industrial', 'Building Fabricators', 208),
	(546, 'Orbital - Installation - Space Farm', 'Crop Harvesters', 77),
	(547, 'Surface - Settlement - Agriculture T1 S', 'Crop Harvesters', 210),
	(548, 'Surface - Settlement - Agriculture T1 M', 'Crop Harvesters', 420),
	(549, 'Surface - Settlement - Agriculture T2 L', 'Crop Harvesters', 630),
	(550, 'Surface - Hub - Civilian', 'Crop Harvesters', 210),
	(551, 'Surface - Planetary Port - Outpost Civilian', 'Emergency Power Cells', 68),
	(552, 'Surface - Planetary Port - Outpost Industrial', 'Emergency Power Cells', 68),
	(553, 'Surface - Planetary Port - Outpost Scientific', 'Emergency Power Cells', 68),
	(554, 'Surface - Planetary Port - Port', 'Emergency Power Cells', 272),
	(555, 'Surface - Settlement - Agriculture T1 S', 'Emergency Power Cells', 84),
	(556, 'Surface - Settlement - Agriculture T1 M', 'Emergency Power Cells', 168),
	(557, 'Surface - Settlement - Agriculture T2 L', 'Emergency Power Cells', 252),
	(558, 'Surface - Settlement - Extraction T1 S', 'Emergency Power Cells', 96),
	(559, 'Surface - Settlement - Extraction T1 M', 'Emergency Power Cells', 192),
	(560, 'Surface - Settlement - Extraction T2 L', 'Emergency Power Cells', 288),
	(561, 'Surface - Settlement - Industrial T1 S', 'Emergency Power Cells', 28),
	(562, 'Surface - Settlement - Industrial T1 M', 'Emergency Power Cells', 56),
	(563, 'Surface - Settlement - Industrial T2 L', 'Emergency Power Cells', 84),
	(564, 'Surface - Settlement - Military T1 S', 'Emergency Power Cells', 24),
	(565, 'Surface - Settlement - Military T1 M', 'Emergency Power Cells', 48),
	(566, 'Surface - Settlement - Military T2 L', 'Emergency Power Cells', 72),
	(567, 'Surface - Settlement - Research Bio T1 S', 'Emergency Power Cells', 27),
	(568, 'Surface - Settlement - Research Bio T1 M', 'Emergency Power Cells', 54),
	(569, 'Surface - Settlement - Research Bio T2 L', 'Emergency Power Cells', 81),
	(570, 'Surface - Settlement - Tourism T1 S', 'Emergency Power Cells', 15),
	(571, 'Surface - Settlement - Tourism T1 M', 'Emergency Power Cells', 30),
	(572, 'Surface - Settlement - Tourism T2 L', 'Emergency Power Cells', 45),
	(573, 'Surface - Hub - Extraction', 'Emergency Power Cells', 42),
	(574, 'Surface - Hub - Civilian', 'Emergency Power Cells', 42),
	(575, 'Surface - Hub - Exploration', 'Emergency Power Cells', 45),
	(576, 'Surface - Hub - Outpost', 'Emergency Power Cells', 49),
	(577, 'Surface - Hub - Scientific', 'Emergency Power Cells', 63),
	(578, 'Surface - Hub - Military', 'Emergency Power Cells', 63),
	(579, 'Surface - Hub - Refinery', 'Emergency Power Cells', 47),
	(580, 'Surface - Hub - High Tech', 'Emergency Power Cells', 59),
	(581, 'Surface - Hub - Industrial', 'Emergency Power Cells', 42),
	(582, 'Orbital - Installation - Mining Outpost', 'Geological Equipment', 26),
	(583, 'Orbital - Installation - Research Station', 'Geological Equipment', 26),
	(584, 'Surface - Settlement - Extraction T1 S', 'Geological Equipment', 52),
	(585, 'Surface - Settlement - Extraction T1 M', 'Geological Equipment', 104),
	(586, 'Surface - Settlement - Extraction T2 L', 'Geological Equipment', 156),
	(587, 'Surface - Settlement - Research Bio T1 S', 'Geological Equipment', 27),
	(588, 'Surface - Settlement - Research Bio T1 M', 'Geological Equipment', 54),
	(589, 'Surface - Settlement - Research Bio T2 L', 'Geological Equipment', 81),
	(590, 'Surface - Hub - Extraction', 'Geological Equipment', 210),
	(591, 'Surface - Hub - Exploration', 'Geological Equipment', 621),
	(592, 'Surface - Hub - Scientific', 'Geological Equipment', 401),
	(593, 'Surface - Settlement - Industrial T1 S', 'Microbial Furnaces', 82),
	(594, 'Surface - Settlement - Industrial T1 M', 'Microbial Furnaces', 164),
	(595, 'Surface - Settlement - Industrial T2 L', 'Microbial Furnaces', 246),
	(596, 'Surface - Hub - Industrial', 'Microbial Furnaces', 415),
	(597, 'Surface - Settlement - Industrial T1 S', 'Mineral Extractors', 164),
	(598, 'Surface - Settlement - Industrial T1 M', 'Mineral Extractors', 328),
	(599, 'Surface - Settlement - Industrial T2 L', 'Mineral Extractors', 492),
	(600, 'Surface - Hub - Industrial', 'Mineral Extractors', 415),
	(601, 'Orbital - Starport - Coriolis', 'Power Generators', 65),
	(602, 'Orbital - Starport - Asteroid Base', 'Power Generators', 65),
	(603, 'Orbital - Starport - Ocellus', 'Power Generators', 130),
	(604, 'Orbital - Starport - Orbis', 'Power Generators', 130),
	(605, 'Orbital - Outpost - Commercial', 'Power Generators', 19),
	(606, 'Orbital - Outpost - Industrial', 'Power Generators', 19),
	(607, 'Orbital - Outpost - Criminal', 'Power Generators', 19),
	(608, 'Orbital - Outpost - Civilian', 'Power Generators', 19),
	(609, 'Orbital - Outpost - Scientific', 'Power Generators', 19),
	(610, 'Orbital - Outpost - Military', 'Power Generators', 19),
	(611, 'Orbital - Installation - Satellite', 'Power Generators', 9),
	(612, 'Orbital - Installation - Comm Station', 'Power Generators', 9),
	(613, 'Orbital - Installation - Space Farm', 'Power Generators', 8),
	(614, 'Orbital - Installation - Pirate Base', 'Power Generators', 8),
	(615, 'Orbital - Installation - Mining Outpost', 'Power Generators', 9),
	(616, 'Orbital - Installation - Relay Station', 'Power Generators', 10),
	(617, 'Orbital - Installation - Military', 'Power Generators', 18),
	(618, 'Orbital - Installation - Security Station', 'Power Generators', 13),
	(619, 'Orbital - Installation - Government', 'Power Generators', 13),
	(620, 'Orbital - Installation - Medical', 'Power Generators', 19),
	(621, 'Orbital - Installation - Research Station', 'Power Generators', 13),
	(622, 'Orbital - Installation - Tourist', 'Power Generators', 13),
	(623, 'Orbital - Installation - Space Bar', 'Power Generators', 13),
	(624, 'Surface - Planetary Port - Outpost Civilian', 'Power Generators', 68),
	(625, 'Surface - Planetary Port - Outpost Industrial', 'Power Generators', 68),
	(626, 'Surface - Planetary Port - Outpost Scientific', 'Power Generators', 68),
	(627, 'Surface - Planetary Port - Port', 'Power Generators', 272),
	(628, 'Surface - Hub - Exploration', 'Power Generators', 32),
	(629, 'Surface - Hub - Outpost', 'Power Generators', 25),
	(630, 'Surface - Hub - Scientific', 'Power Generators', 36),
	(631, 'Surface - Hub - Military', 'Power Generators', 38),
	(632, 'Surface - Hub - Refinery', 'Power Generators', 28),
	(633, 'Surface - Hub - High Tech', 'Power Generators', 27),
	(634, 'Surface - Hub - Industrial', 'Power Generators', 25),
	(635, 'Surface - Settlement - Industrial T1 S', 'Thermal Cooling Units', 14),
	(636, 'Surface - Settlement - Industrial T1 M', 'Thermal Cooling Units', 28),
	(637, 'Surface - Settlement - Industrial T2 L', 'Thermal Cooling Units', 42),
	(638, 'Surface - Hub - Refinery', 'Thermal Cooling Units', 103),
	(639, 'Surface - Hub - High Tech', 'Thermal Cooling Units', 211),
	(640, 'Surface - Hub - Industrial', 'Thermal Cooling Units', 117),
	(641, 'Orbital - Starport - Coriolis', 'Water Purifiers', 105),
	(642, 'Orbital - Starport - Asteroid Base', 'Water Purifiers', 105),
	(643, 'Orbital - Starport - Ocellus', 'Water Purifiers', 210),
	(644, 'Orbital - Starport - Orbis', 'Water Purifiers', 210),
	(645, 'Orbital - Outpost - Commercial', 'Water Purifiers', 38),
	(646, 'Orbital - Outpost - Industrial', 'Water Purifiers', 38),
	(647, 'Orbital - Outpost - Criminal', 'Water Purifiers', 38),
	(648, 'Orbital - Outpost - Civilian', 'Water Purifiers', 38),
	(649, 'Orbital - Outpost - Scientific', 'Water Purifiers', 38),
	(650, 'Orbital - Outpost - Military', 'Water Purifiers', 38),
	(651, 'Orbital - Installation - Satellite', 'Water Purifiers', 13),
	(652, 'Orbital - Installation - Comm Station', 'Water Purifiers', 13),
	(653, 'Orbital - Installation - Space Farm', 'Water Purifiers', 31),
	(654, 'Orbital - Installation - Pirate Base', 'Water Purifiers', 16),
	(655, 'Orbital - Installation - Mining Outpost', 'Water Purifiers', 22),
	(656, 'Orbital - Installation - Relay Station', 'Water Purifiers', 15),
	(657, 'Orbital - Installation - Military', 'Water Purifiers', 42),
	(658, 'Orbital - Installation - Security Station', 'Water Purifiers', 19),
	(659, 'Orbital - Installation - Government', 'Water Purifiers', 31),
	(660, 'Orbital - Installation - Medical', 'Water Purifiers', 38),
	(661, 'Orbital - Installation - Research Station', 'Water Purifiers', 38),
	(662, 'Orbital - Installation - Tourist', 'Water Purifiers', 39),
	(663, 'Orbital - Installation - Space Bar', 'Water Purifiers', 38),
	(664, 'Orbital - Installation - Space Farm', 'Agri-Medicines', 115),
	(665, 'Surface - Hub - Civilian', 'Agri-Medicines', 235),
	(666, 'Orbital - Installation - Military', 'Basic Medicines', 24),
	(667, 'Orbital - Installation - Medical', 'Basic Medicines', 50),
	(668, 'Orbital - Installation - Research Station', 'Basic Medicines', 13),
	(669, 'Surface - Settlement - Military T1 S', 'Basic Medicines', 36),
	(670, 'Surface - Settlement - Military T1 M', 'Basic Medicines', 72),
	(671, 'Surface - Settlement - Military T2 L', 'Basic Medicines', 108),
	(672, 'Surface - Settlement - Research Bio T1 S', 'Basic Medicines', 14),
	(673, 'Surface - Settlement - Research Bio T1 M', 'Basic Medicines', 28),
	(674, 'Surface - Settlement - Research Bio T2 L', 'Basic Medicines', 42),
	(675, 'Surface - Hub - Scientific', 'Basic Medicines', 72),
	(676, 'Surface - Hub - Military', 'Basic Medicines', 109),
	(677, 'Orbital - Installation - Military', 'Combat Stabilizers', 48),
	(678, 'Orbital - Installation - Security Station', 'Combat Stabilizers', 25),
	(679, 'Orbital - Installation - Medical', 'Combat Stabilizers', 19),
	(680, 'Surface - Settlement - Military T1 S', 'Combat Stabilizers', 36),
	(681, 'Surface - Settlement - Military T1 M', 'Combat Stabilizers', 72),
	(682, 'Surface - Settlement - Military T2 L', 'Combat Stabilizers', 108),
	(683, 'Surface - Hub - Military', 'Combat Stabilizers', 25),
	(684, 'Orbital - Starport - Coriolis', 'Aluminium', 10055),
	(685, 'Orbital - Starport - Asteroid Base', 'Aluminium', 10055),
	(686, 'Orbital - Starport - Ocellus', 'Aluminium', 40220),
	(687, 'Orbital - Starport - Orbis', 'Aluminium', 40220),
	(688, 'Orbital - Outpost - Commercial', 'Aluminium', 515),
	(689, 'Orbital - Outpost - Industrial', 'Aluminium', 515),
	(690, 'Orbital - Outpost - Criminal', 'Aluminium', 515),
	(691, 'Orbital - Outpost - Civilian', 'Aluminium', 515),
	(692, 'Orbital - Outpost - Scientific', 'Aluminium', 515),
	(693, 'Orbital - Outpost - Military', 'Aluminium', 515),
	(694, 'Orbital - Installation - Satellite', 'Aluminium', 1322),
	(695, 'Orbital - Installation - Comm Station', 'Aluminium', 1322),
	(696, 'Orbital - Installation - Space Farm', 'Aluminium', 842),
	(697, 'Orbital - Installation - Pirate Base', 'Aluminium', 1233),
	(698, 'Orbital - Installation - Mining Outpost', 'Aluminium', 921),
	(699, 'Orbital - Installation - Relay Station', 'Aluminium', 1033),
	(700, 'Orbital - Installation - Military', 'Aluminium', 1317),
	(701, 'Orbital - Installation - Security Station', 'Aluminium', 1774),
	(702, 'Orbital - Installation - Government', 'Aluminium', 1959),
	(703, 'Orbital - Installation - Medical', 'Aluminium', 1357),
	(704, 'Orbital - Installation - Research Station', 'Aluminium', 1380),
	(705, 'Orbital - Installation - Tourist', 'Aluminium', 1269),
	(706, 'Orbital - Installation - Space Bar', 'Aluminium', 1217),
	(707, 'Surface - Planetary Port - Outpost Civilian', 'Aluminium', 7047),
	(708, 'Surface - Planetary Port - Outpost Industrial', 'Aluminium', 7047),
	(709, 'Surface - Planetary Port - Outpost Scientific', 'Aluminium', 7047),
	(710, 'Surface - Planetary Port - Port', 'Aluminium', 42282),
	(711, 'Surface - Settlement - Agriculture T1 S', 'Aluminium', 559),
	(712, 'Surface - Settlement - Agriculture T1 M', 'Aluminium', 1118),
	(713, 'Surface - Settlement - Agriculture T2 L', 'Aluminium', 1677),
	(714, 'Surface - Settlement - Extraction T1 S', 'Aluminium', 632),
	(715, 'Surface - Settlement - Extraction T1 M', 'Aluminium', 1264),
	(716, 'Surface - Settlement - Extraction T2 L', 'Aluminium', 1896),
	(717, 'Surface - Settlement - Industrial T1 S', 'Aluminium', 585),
	(718, 'Surface - Settlement - Industrial T1 M', 'Aluminium', 1170),
	(719, 'Surface - Settlement - Industrial T2 L', 'Aluminium', 1755),
	(720, 'Surface - Settlement - Military T1 S', 'Aluminium', 593),
	(721, 'Surface - Settlement - Military T1 M', 'Aluminium', 1186),
	(722, 'Surface - Settlement - Military T2 L', 'Aluminium', 1779),
	(723, 'Surface - Settlement - Research Bio T1 S', 'Aluminium', 607),
	(724, 'Surface - Settlement - Research Bio T1 M', 'Aluminium', 1214),
	(725, 'Surface - Settlement - Research Bio T2 L', 'Aluminium', 1821),
	(726, 'Surface - Settlement - Tourism T1 S', 'Aluminium', 509),
	(727, 'Surface - Settlement - Tourism T1 M', 'Aluminium', 1018),
	(728, 'Surface - Settlement - Tourism T2 L', 'Aluminium', 1527),
	(729, 'Surface - Hub - Extraction', 'Aluminium', 2352),
	(730, 'Surface - Hub - Civilian', 'Aluminium', 2433),
	(731, 'Surface - Hub - Exploration', 'Aluminium', 2483),
	(732, 'Surface - Hub - Outpost', 'Aluminium', 2797),
	(733, 'Surface - Hub - Scientific', 'Aluminium', 2581),
	(734, 'Surface - Hub - Military', 'Aluminium', 2414),
	(735, 'Surface - Hub - Refinery', 'Aluminium', 2697),
	(736, 'Surface - Hub - High Tech', 'Aluminium', 2512),
	(737, 'Surface - Hub - Industrial', 'Aluminium', 2407),
	(738, 'Orbital - Starport - Coriolis', 'Copper', 644),
	(739, 'Orbital - Starport - Asteroid Base', 'Copper', 644),
	(740, 'Orbital - Starport - Ocellus', 'Copper', 2576),
	(741, 'Orbital - Starport - Orbis', 'Copper', 2576),
	(742, 'Orbital - Outpost - Commercial', 'Copper', 218),
	(743, 'Orbital - Outpost - Industrial', 'Copper', 217),
	(744, 'Orbital - Outpost - Criminal', 'Copper', 218),
	(745, 'Orbital - Outpost - Civilian', 'Copper', 218),
	(746, 'Orbital - Outpost - Scientific', 'Copper', 218),
	(747, 'Orbital - Outpost - Military', 'Copper', 218),
	(748, 'Orbital - Installation - Satellite', 'Copper', 85),
	(749, 'Orbital - Installation - Comm Station', 'Copper', 85),
	(750, 'Orbital - Installation - Space Farm', 'Copper', 46),
	(751, 'Orbital - Installation - Pirate Base', 'Copper', 57),
	(752, 'Orbital - Installation - Mining Outpost', 'Copper', 52),
	(753, 'Orbital - Installation - Relay Station', 'Copper', 88),
	(754, 'Orbital - Installation - Military', 'Copper', 131),
	(755, 'Orbital - Installation - Security Station', 'Copper', 122),
	(756, 'Orbital - Installation - Government', 'Copper', 93),
	(757, 'Orbital - Installation - Medical', 'Copper', 112),
	(758, 'Orbital - Installation - Research Station', 'Copper', 126),
	(759, 'Orbital - Installation - Tourist', 'Copper', 78),
	(760, 'Orbital - Installation - Space Bar', 'Copper', 75),
	(761, 'Surface - Planetary Port - Outpost Civilian', 'Copper', 407),
	(762, 'Surface - Planetary Port - Outpost Industrial', 'Copper', 407),
	(763, 'Surface - Planetary Port - Outpost Scientific', 'Copper', 407),
	(764, 'Surface - Planetary Port - Port', 'Copper', 2442),
	(765, 'Surface - Settlement - Agriculture T1 S', 'Copper', 21),
	(766, 'Surface - Settlement - Agriculture T1 M', 'Copper', 42),
	(767, 'Surface - Settlement - Agriculture T2 L', 'Copper', 63),
	(768, 'Surface - Settlement - Extraction T1 S', 'Copper', 30),
	(769, 'Surface - Settlement - Extraction T1 M', 'Copper', 60),
	(770, 'Surface - Settlement - Extraction T2 L', 'Copper', 90),
	(771, 'Surface - Settlement - Industrial T1 S', 'Copper', 28),
	(772, 'Surface - Settlement - Industrial T1 M', 'Copper', 56),
	(773, 'Surface - Settlement - Industrial T2 L', 'Copper', 84),
	(774, 'Surface - Settlement - Military T1 S', 'Copper', 30),
	(775, 'Surface - Settlement - Military T1 M', 'Copper', 60),
	(776, 'Surface - Settlement - Military T2 L', 'Copper', 90),
	(777, 'Surface - Settlement - Research Bio T1 S', 'Copper', 34),
	(778, 'Surface - Settlement - Research Bio T1 M', 'Copper', 68),
	(779, 'Surface - Settlement - Research Bio T2 L', 'Copper', 102),
	(780, 'Surface - Settlement - Tourism T1 S', 'Copper', 22),
	(781, 'Surface - Settlement - Tourism T1 M', 'Copper', 44),
	(782, 'Surface - Settlement - Tourism T2 L', 'Copper', 66),
	(783, 'Surface - Hub - Extraction', 'Copper', 84),
	(784, 'Surface - Hub - Civilian', 'Copper', 68),
	(785, 'Surface - Hub - Exploration', 'Copper', 178),
	(786, 'Surface - Hub - Outpost', 'Copper', 78),
	(787, 'Surface - Hub - Scientific', 'Copper', 112),
	(788, 'Surface - Hub - Military', 'Copper', 105),
	(789, 'Surface - Hub - Refinery', 'Copper', 93),
	(790, 'Surface - Hub - High Tech', 'Copper', 113),
	(791, 'Surface - Hub - Industrial', 'Copper', 83),
	(792, 'Orbital - Starport - Coriolis', 'Steel', 14076),
	(793, 'Orbital - Starport - Asteroid Base', 'Steel', 14076),
	(794, 'Orbital - Starport - Ocellus', 'Steel', 56304),
	(795, 'Orbital - Starport - Orbis', 'Steel', 56304),
	(796, 'Orbital - Outpost - Commercial', 'Steel', 5588),
	(797, 'Orbital - Outpost - Industrial', 'Steel', 5588),
	(798, 'Orbital - Outpost - Criminal', 'Steel', 5588),
	(799, 'Orbital - Outpost - Civilian', 'Steel', 5588),
	(800, 'Orbital - Outpost - Scientific', 'Steel', 5588),
	(801, 'Orbital - Outpost - Military', 'Steel', 5588),
	(802, 'Orbital - Installation - Satellite', 'Steel', 2542),
	(803, 'Orbital - Installation - Comm Station', 'Steel', 2542),
	(804, 'Orbital - Installation - Space Farm', 'Steel', 1912),
	(805, 'Orbital - Installation - Pirate Base', 'Steel', 1707),
	(806, 'Orbital - Installation - Mining Outpost', 'Steel', 2141),
	(807, 'Orbital - Installation - Relay Station', 'Steel', 2437),
	(808, 'Orbital - Installation - Military', 'Steel', 2966),
	(809, 'Orbital - Installation - Security Station', 'Steel', 3645),
	(810, 'Orbital - Installation - Government', 'Steel', 3080),
	(811, 'Orbital - Installation - Medical', 'Steel', 3084),
	(812, 'Orbital - Installation - Research Station', 'Steel', 3136),
	(813, 'Orbital - Installation - Tourist', 'Steel', 2598),
	(814, 'Orbital - Installation - Space Bar', 'Steel', 2483),
	(815, 'Surface - Planetary Port - Outpost Civilian', 'Steel', 10164),
	(816, 'Surface - Planetary Port - Outpost Industrial', 'Steel', 10164),
	(817, 'Surface - Planetary Port - Outpost Scientific', 'Steel', 10164),
	(818, 'Surface - Planetary Port - Port', 'Steel', 60984),
	(819, 'Surface - Settlement - Agriculture T1 S', 'Steel', 768),
	(820, 'Surface - Settlement - Agriculture T1 M', 'Steel', 1536),
	(821, 'Surface - Settlement - Agriculture T2 L', 'Steel', 2304),
	(822, 'Surface - Settlement - Extraction T1 S', 'Steel', 1028),
	(823, 'Surface - Settlement - Extraction T1 M', 'Steel', 2056),
	(824, 'Surface - Settlement - Extraction T2 L', 'Steel', 3084),
	(825, 'Surface - Settlement - Industrial T1 S', 'Steel', 1019),
	(826, 'Surface - Settlement - Industrial T1 M', 'Steel', 2038),
	(827, 'Surface - Settlement - Industrial T2 L', 'Steel', 3057),
	(828, 'Surface - Settlement - Military T1 S', 'Steel', 949),
	(829, 'Surface - Settlement - Military T1 M', 'Steel', 1898),
	(830, 'Surface - Settlement - Military T2 L', 'Steel', 2847),
	(831, 'Surface - Settlement - Research Bio T1 S', 'Steel', 945),
	(832, 'Surface - Settlement - Research Bio T1 M', 'Steel', 1890),
	(833, 'Surface - Settlement - Research Bio T2 L', 'Steel', 2835),
	(834, 'Surface - Settlement - Tourism T1 S', 'Steel', 707),
	(835, 'Surface - Settlement - Tourism T1 M', 'Steel', 1414),
	(836, 'Surface - Settlement - Tourism T2 L', 'Steel', 2121),
	(837, 'Surface - Hub - Extraction', 'Steel', 3359),
	(838, 'Surface - Hub - Civilian', 'Steel', 3775),
	(839, 'Surface - Hub - Exploration', 'Steel', 3547),
	(840, 'Surface - Hub - Outpost', 'Steel', 4051),
	(841, 'Surface - Hub - Scientific', 'Steel', 3560),
	(842, 'Surface - Hub - Military', 'Steel', 3746),
	(843, 'Surface - Hub - Refinery', 'Steel', 3720),
	(844, 'Surface - Hub - High Tech', 'Steel', 3768),
	(845, 'Surface - Hub - Industrial', 'Steel', 3320),
	(846, 'Orbital - Starport - Coriolis', 'Titanium', 8205),
	(847, 'Orbital - Starport - Asteroid Base', 'Titanium', 8205),
	(848, 'Orbital - Starport - Ocellus', 'Titanium', 32820),
	(849, 'Orbital - Starport - Orbis', 'Titanium', 32820),
	(850, 'Orbital - Outpost - Commercial', 'Titanium', 4843),
	(851, 'Orbital - Outpost - Industrial', 'Titanium', 4843),
	(852, 'Orbital - Outpost - Criminal', 'Titanium', 4843),
	(853, 'Orbital - Outpost - Civilian', 'Titanium', 4843),
	(854, 'Orbital - Outpost - Scientific', 'Titanium', 4843),
	(855, 'Orbital - Outpost - Military', 'Titanium', 4843),
	(856, 'Orbital - Installation - Satellite', 'Titanium', 1525),
	(857, 'Orbital - Installation - Comm Station', 'Titanium', 1525),
	(858, 'Orbital - Installation - Space Farm', 'Titanium', 1453),
	(859, 'Orbital - Installation - Pirate Base', 'Titanium', 1594),
	(860, 'Orbital - Installation - Mining Outpost', 'Titanium', 1628),
	(861, 'Orbital - Installation - Relay Station', 'Titanium', 1755),
	(862, 'Orbital - Installation - Military', 'Titanium', 2373),
	(863, 'Orbital - Installation - Security Station', 'Titanium', 2309),
	(864, 'Orbital - Installation - Government', 'Titanium', 2341),
	(865, 'Orbital - Installation - Medical', 'Titanium', 2282),
	(866, 'Orbital - Installation - Research Station', 'Titanium', 2383),
	(867, 'Orbital - Installation - Tourist', 'Titanium', 1813),
	(868, 'Orbital - Installation - Space Bar', 'Titanium', 1738),
	(869, 'Surface - Planetary Port - Outpost Civilian', 'Titanium', 5760),
	(870, 'Surface - Planetary Port - Outpost Industrial', 'Titanium', 5760),
	(871, 'Surface - Planetary Port - Outpost Scientific', 'Titanium', 5760),
	(872, 'Surface - Planetary Port - Port', 'Titanium', 34560),
	(873, 'Orbital - Installation - Research Station', 'Advanced Catalysers', 44),
	(874, 'Surface - Settlement - Industrial T1 S', 'Advanced Catalysers', 41),
	(875, 'Surface - Settlement - Industrial T1 M', 'Advanced Catalysers', 82),
	(876, 'Surface - Settlement - Industrial T2 L', 'Advanced Catalysers', 123),
	(877, 'Surface - Settlement - Research Bio T1 S', 'Advanced Catalysers', 95),
	(878, 'Surface - Settlement - Research Bio T1 M', 'Advanced Catalysers', 190),
	(879, 'Surface - Settlement - Research Bio T2 L', 'Advanced Catalysers', 285),
	(880, 'Surface - Hub - Scientific', 'Advanced Catalysers', 170),
	(881, 'Surface - Hub - Refinery', 'Advanced Catalysers', 112),
	(882, 'Orbital - Installation - Mining Outpost', 'Bioreducing Lichen', 172),
	(883, 'Surface - Settlement - Extraction T1 S', 'Bioreducing Lichen', 162),
	(884, 'Surface - Settlement - Extraction T1 M', 'Bioreducing Lichen', 324),
	(885, 'Surface - Settlement - Extraction T2 L', 'Bioreducing Lichen', 486),
	(886, 'Surface - Hub - Extraction', 'Bioreducing Lichen', 714),
	(887, 'Orbital - Starport - Coriolis', 'Computer Components', 145),
	(888, 'Orbital - Starport - Asteroid Base', 'Computer Components', 145),
	(889, 'Orbital - Starport - Ocellus', 'Computer Components', 290),
	(890, 'Orbital - Starport - Orbis', 'Computer Components', 290),
	(891, 'Orbital - Outpost - Commercial', 'Computer Components', 50),
	(892, 'Orbital - Outpost - Industrial', 'Computer Components', 50),
	(893, 'Orbital - Outpost - Criminal', 'Computer Components', 50),
	(894, 'Orbital - Outpost - Civilian', 'Computer Components', 50),
	(895, 'Orbital - Outpost - Scientific', 'Computer Components', 50),
	(896, 'Orbital - Outpost - Military', 'Computer Components', 50),
	(897, 'Orbital - Installation - Satellite', 'Computer Components', 22),
	(898, 'Orbital - Installation - Comm Station', 'Computer Components', 22),
	(899, 'Orbital - Installation - Space Farm', 'Computer Components', 12),
	(900, 'Orbital - Installation - Pirate Base', 'Computer Components', 19),
	(901, 'Orbital - Installation - Mining Outpost', 'Computer Components', 13),
	(902, 'Orbital - Installation - Relay Station', 'Computer Components', 25),
	(903, 'Orbital - Installation - Military', 'Computer Components', 42),
	(904, 'Orbital - Installation - Security Station', 'Computer Components', 31),
	(905, 'Orbital - Installation - Government', 'Computer Components', 13),
	(906, 'Orbital - Installation - Medical', 'Computer Components', 31),
	(907, 'Orbital - Installation - Research Station', 'Computer Components', 38),
	(908, 'Orbital - Installation - Tourist', 'Computer Components', 13),
	(909, 'Orbital - Installation - Space Bar', 'Computer Components', 13),
	(910, 'Surface - Planetary Port - Outpost Civilian', 'Computer Components', 102),
	(911, 'Surface - Planetary Port - Outpost Industrial', 'Computer Components', 102),
	(912, 'Surface - Planetary Port - Outpost Scientific', 'Computer Components', 102),
	(913, 'Surface - Planetary Port - Port', 'Computer Components', 408),
	(914, 'Surface - Settlement - Agriculture T1 S', 'Computer Components', 14),
	(915, 'Surface - Settlement - Agriculture T1 M', 'Computer Components', 28),
	(916, 'Surface - Settlement - Agriculture T2 L', 'Computer Components', 42),
	(917, 'Surface - Settlement - Extraction T1 S', 'Computer Components', 30),
	(918, 'Surface - Settlement - Extraction T1 M', 'Computer Components', 60),
	(919, 'Surface - Settlement - Extraction T2 L', 'Computer Components', 90),
	(920, 'Surface - Settlement - Industrial T1 S', 'Computer Components', 28),
	(921, 'Surface - Settlement - Industrial T1 M', 'Computer Components', 56),
	(922, 'Surface - Settlement - Industrial T2 L', 'Computer Components', 84),
	(923, 'Surface - Settlement - Military T1 S', 'Computer Components', 42),
	(924, 'Surface - Settlement - Military T1 M', 'Computer Components', 84),
	(925, 'Surface - Settlement - Military T2 L', 'Computer Components', 126),
	(926, 'Surface - Settlement - Research Bio T1 S', 'Computer Components', 41),
	(927, 'Surface - Settlement - Research Bio T1 M', 'Computer Components', 82),
	(928, 'Surface - Settlement - Research Bio T2 L', 'Computer Components', 123),
	(929, 'Surface - Settlement - Tourism T1 S', 'Computer Components', 15),
	(930, 'Surface - Settlement - Tourism T1 M', 'Computer Components', 30),
	(931, 'Surface - Settlement - Tourism T2 L', 'Computer Components', 45),
	(932, 'Surface - Hub - Extraction', 'Computer Components', 38),
	(933, 'Surface - Hub - Civilian', 'Computer Components', 21),
	(934, 'Surface - Hub - Exploration', 'Computer Components', 49),
	(935, 'Surface - Hub - Outpost', 'Computer Components', 25),
	(936, 'Surface - Hub - Scientific', 'Computer Components', 67),
	(937, 'Surface - Hub - Military', 'Computer Components', 75),
	(938, 'Surface - Hub - Refinery', 'Computer Components', 42),
	(939, 'Surface - Hub - High Tech', 'Computer Components', 68),
	(940, 'Surface - Hub - Industrial', 'Computer Components', 38),
	(941, 'Orbital - Installation - Mining Outpost', 'H.E. Suits', 13),
	(942, 'Orbital - Installation - Medical', 'H.E. Suits', 25),
	(943, 'Orbital - Installation - Research Station', 'H.E. Suits', 32),
	(944, 'Surface - Settlement - Extraction T1 S', 'H.E. Suits', 15),
	(945, 'Surface - Settlement - Extraction T1 M', 'H.E. Suits', 30),
	(946, 'Surface - Settlement - Extraction T2 L', 'H.E. Suits', 45),
	(947, 'Surface - Settlement - Industrial T1 S', 'H.E. Suits', 14),
	(948, 'Surface - Settlement - Industrial T1 M', 'H.E. Suits', 28),
	(949, 'Surface - Settlement - Industrial T2 L', 'H.E. Suits', 42),
	(950, 'Surface - Settlement - Research Bio T1 S', 'H.E. Suits', 27),
	(951, 'Surface - Settlement - Research Bio T1 M', 'H.E. Suits', 54),
	(952, 'Surface - Settlement - Research Bio T2 L', 'H.E. Suits', 81),
	(953, 'Surface - Hub - Extraction', 'H.E. Suits', 126),
	(954, 'Surface - Hub - Exploration', 'H.E. Suits', 249),
	(955, 'Surface - Hub - Scientific', 'H.E. Suits', 156),
	(956, 'Surface - Hub - Refinery', 'H.E. Suits', 117),
	(957, 'Surface - Hub - Industrial', 'H.E. Suits', 83),
	(958, 'Surface - Planetary Port - Outpost Civilian', 'Land Enrichment Systems', 68),
	(959, 'Surface - Planetary Port - Outpost Industrial', 'Land Enrichment Systems', 68),
	(960, 'Surface - Planetary Port - Outpost Scientific', 'Land Enrichment Systems', 68),
	(961, 'Surface - Planetary Port - Port', 'Land Enrichment Systems', 272),
	(962, 'Surface - Settlement - Agriculture T1 S', 'Land Enrichment Systems', 70),
	(963, 'Surface - Settlement - Agriculture T1 M', 'Land Enrichment Systems', 140),
	(964, 'Surface - Settlement - Agriculture T2 L', 'Land Enrichment Systems', 210),
	(965, 'Orbital - Starport - Coriolis', 'Medical Diagnostic Equipment', 25),
	(966, 'Orbital - Starport - Asteroid Base', 'Medical Diagnostic Equipment', 25),
	(967, 'Orbital - Starport - Ocellus', 'Medical Diagnostic Equipment', 50),
	(968, 'Orbital - Starport - Orbis', 'Medical Diagnostic Equipment', 50),
	(969, 'Orbital - Outpost - Commercial', 'Medical Diagnostic Equipment', 13),
	(970, 'Orbital - Outpost - Industrial', 'Medical Diagnostic Equipment', 13),
	(971, 'Orbital - Outpost - Criminal', 'Medical Diagnostic Equipment', 13),
	(972, 'Orbital - Outpost - Civilian', 'Medical Diagnostic Equipment', 13),
	(973, 'Orbital - Outpost - Scientific', 'Medical Diagnostic Equipment', 13),
	(974, 'Orbital - Outpost - Military', 'Medical Diagnostic Equipment', 13),
	(975, 'Orbital - Installation - Medical', 'Medical Diagnostic Equipment', 99),
	(976, 'Orbital - Installation - Research Station', 'Medical Diagnostic Equipment', 51),
	(977, 'Surface - Planetary Port - Outpost Civilian', 'Medical Diagnostic Equipment', 48),
	(978, 'Surface - Planetary Port - Outpost Industrial', 'Medical Diagnostic Equipment', 48),
	(979, 'Surface - Planetary Port - Outpost Scientific', 'Medical Diagnostic Equipment', 48),
	(980, 'Surface - Planetary Port - Port', 'Medical Diagnostic Equipment', 192),
	(981, 'Surface - Settlement - Research Bio T1 S', 'Medical Diagnostic Equipment', 41),
	(982, 'Surface - Settlement - Research Bio T1 M', 'Medical Diagnostic Equipment', 82),
	(983, 'Surface - Settlement - Research Bio T2 L', 'Medical Diagnostic Equipment', 123),
	(984, 'Surface - Hub - Scientific', 'Medical Diagnostic Equipment', 161),
	(985, 'Orbital - Installation - Satellite', 'Micro Controllers', 13),
	(986, 'Orbital - Installation - Comm Station', 'Micro Controllers', 13),
	(987, 'Orbital - Installation - Military', 'Micro Controllers', 18),
	(988, 'Orbital - Installation - Research Station', 'Micro Controllers', 13),
	(989, 'Surface - Settlement - Industrial T1 S', 'Micro Controllers', 14),
	(990, 'Surface - Settlement - Industrial T1 M', 'Micro Controllers', 28),
	(991, 'Surface - Settlement - Industrial T2 L', 'Micro Controllers', 42),
	(992, 'Surface - Settlement - Military T1 S', 'Micro Controllers', 12),
	(993, 'Surface - Settlement - Military T1 M', 'Micro Controllers', 24),
	(994, 'Surface - Settlement - Military T2 L', 'Micro Controllers', 36),
	(995, 'Surface - Settlement - Research Bio T1 S', 'Micro Controllers', 14),
	(996, 'Surface - Settlement - Research Bio T1 M', 'Micro Controllers', 28),
	(997, 'Surface - Settlement - Research Bio T2 L', 'Micro Controllers', 42),
	(998, 'Surface - Hub - Scientific', 'Micro Controllers', 49),
	(999, 'Surface - Hub - Military', 'Micro Controllers', 55),
	(1000, 'Surface - Hub - High Tech', 'Micro Controllers', 90),
	(1001, 'Surface - Hub - Industrial', 'Micro Controllers', 50),
	(1002, 'Orbital - Installation - Mining Outpost', 'Muon Imager', 43),
	(1003, 'Orbital - Installation - Research Station', 'Muon Imager', 38),
	(1004, 'Surface - Settlement - Extraction T1 S', 'Muon Imager', 45),
	(1005, 'Surface - Settlement - Extraction T1 M', 'Muon Imager', 90),
	(1006, 'Surface - Settlement - Extraction T2 L', 'Muon Imager', 135),
	(1007, 'Surface - Settlement - Research Bio T1 S', 'Muon Imager', 95),
	(1008, 'Surface - Settlement - Research Bio T1 M', 'Muon Imager', 190),
	(1009, 'Surface - Settlement - Research Bio T2 L', 'Muon Imager', 285),
	(1010, 'Surface - Hub - Extraction', 'Muon Imager', 160),
	(1011, 'Surface - Hub - Scientific', 'Muon Imager', 107),
	(1012, 'Orbital - Installation - Mining Outpost', 'Resonating Separators', 22),
	(1013, 'Surface - Settlement - Industrial T1 S', 'Resonating Separators', 14),
	(1014, 'Surface - Settlement - Industrial T1 M', 'Resonating Separators', 28),
	(1015, 'Surface - Settlement - Industrial T2 L', 'Resonating Separators', 42),
	(1016, 'Surface - Hub - Refinery', 'Resonating Separators', 84),
	(1017, 'Orbital - Installation - Mining Outpost', 'Robotics', 60),
	(1018, 'Surface - Settlement - Extraction T1 S', 'Robotics', 59),
	(1019, 'Surface - Settlement - Extraction T1 M', 'Robotics', 118),
	(1020, 'Surface - Settlement - Extraction T2 L', 'Robotics', 177),
	(1021, 'Surface - Settlement - Industrial T1 S', 'Robotics', 55),
	(1022, 'Surface - Settlement - Industrial T1 M', 'Robotics', 110),
	(1023, 'Surface - Settlement - Industrial T2 L', 'Robotics', 165),
	(1024, 'Surface - Hub - Extraction', 'Robotics', 252),
	(1025, 'Surface - Hub - Refinery', 'Robotics', 419),
	(1026, 'Surface - Hub - High Tech', 'Robotics', 449),
	(1027, 'Surface - Hub - Industrial', 'Robotics', 332),
	(1028, 'Surface - Planetary Port - Outpost Civilian', 'Structural Regulators', 678),
	(1029, 'Surface - Planetary Port - Outpost Industrial', 'Structural Regulators', 678),
	(1030, 'Surface - Planetary Port - Outpost Scientific', 'Structural Regulators', 678),
	(1031, 'Surface - Planetary Port - Port', 'Structural Regulators', 2712),
	(1032, 'Surface - Settlement - Agriculture T1 S', 'Structural Regulators', 56),
	(1033, 'Surface - Settlement - Agriculture T1 M', 'Structural Regulators', 112),
	(1034, 'Surface - Settlement - Agriculture T2 L', 'Structural Regulators', 168),
	(1035, 'Surface - Settlement - Extraction T1 S', 'Structural Regulators', 74),
	(1036, 'Surface - Settlement - Extraction T1 M', 'Structural Regulators', 148),
	(1037, 'Surface - Settlement - Extraction T2 L', 'Structural Regulators', 222),
	(1038, 'Surface - Settlement - Industrial T1 S', 'Structural Regulators', 68),
	(1039, 'Surface - Settlement - Industrial T1 M', 'Structural Regulators', 136),
	(1040, 'Surface - Settlement - Industrial T2 L', 'Structural Regulators', 204),
	(1041, 'Surface - Settlement - Military T1 S', 'Structural Regulators', 101),
	(1042, 'Surface - Settlement - Military T1 M', 'Structural Regulators', 202),
	(1043, 'Surface - Settlement - Military T2 L', 'Structural Regulators', 303),
	(1044, 'Surface - Settlement - Research Bio T1 S', 'Structural Regulators', 81),
	(1045, 'Surface - Settlement - Research Bio T1 M', 'Structural Regulators', 162),
	(1046, 'Surface - Settlement - Research Bio T2 L', 'Structural Regulators', 243),
	(1047, 'Surface - Settlement - Tourism T1 S', 'Structural Regulators', 57),
	(1048, 'Surface - Settlement - Tourism T1 M', 'Structural Regulators', 114),
	(1049, 'Surface - Settlement - Tourism T2 L', 'Structural Regulators', 171),
	(1050, 'Surface - Hub - Extraction', 'Structural Regulators', 504),
	(1051, 'Surface - Hub - Civilian', 'Structural Regulators', 336),
	(1052, 'Surface - Hub - Exploration', 'Structural Regulators', 267),
	(1053, 'Surface - Hub - Outpost', 'Structural Regulators', 338),
	(1054, 'Surface - Hub - Scientific', 'Structural Regulators', 445),
	(1055, 'Surface - Hub - Military', 'Structural Regulators', 542),
	(1056, 'Surface - Hub - Refinery', 'Structural Regulators', 465),
	(1057, 'Surface - Hub - High Tech', 'Structural Regulators', 404),
	(1058, 'Surface - Hub - Industrial', 'Structural Regulators', 498),
	(1059, 'Orbital - Installation - Military', 'Military Grade Fabrics', 36),
	(1060, 'Orbital - Installation - Security Station', 'Military Grade Fabrics', 19),
	(1061, 'Surface - Settlement - Military T1 S', 'Military Grade Fabrics', 24),
	(1062, 'Surface - Settlement - Military T1 M', 'Military Grade Fabrics', 48),
	(1063, 'Surface - Settlement - Military T2 L', 'Military Grade Fabrics', 72),
	(1064, 'Surface - Hub - Military', 'Military Grade Fabrics', 42),
	(1065, 'Orbital - Installation - Space Farm', 'Biowaste', 153),
	(1066, 'Surface - Settlement - Agriculture T1 S', 'Biowaste', 280),
	(1067, 'Surface - Settlement - Agriculture T1 M', 'Biowaste', 560),
	(1068, 'Surface - Settlement - Agriculture T2 L', 'Biowaste', 840),
	(1069, 'Surface - Hub - Civilian', 'Biowaste', 630),
	(1070, 'Orbital - Installation - Pirate Base', 'Battle Weapons', 23),
	(1071, 'Orbital - Installation - Military', 'Battle Weapons', 30),
	(1072, 'Orbital - Installation - Security Station', 'Battle Weapons', 19),
	(1073, 'Surface - Settlement - Military T1 S', 'Battle Weapons', 24),
	(1074, 'Surface - Settlement - Military T1 M', 'Battle Weapons', 48),
	(1075, 'Surface - Settlement - Military T2 L', 'Battle Weapons', 72),
	(1076, 'Surface - Hub - Military', 'Battle Weapons', 42),
	(1077, 'Orbital - Starport - Coriolis', 'Non-Lethal Weapons', 25),
	(1078, 'Orbital - Starport - Asteroid Base', 'Non-Lethal Weapons', 25),
	(1079, 'Orbital - Starport - Ocellus', 'Non-Lethal Weapons', 50),
	(1080, 'Orbital - Starport - Orbis', 'Non-Lethal Weapons', 50),
	(1081, 'Orbital - Outpost - Commercial', 'Non-Lethal Weapons', 13),
	(1082, 'Orbital - Outpost - Industrial', 'Non-Lethal Weapons', 13),
	(1083, 'Orbital - Outpost - Criminal', 'Non-Lethal Weapons', 13),
	(1084, 'Orbital - Outpost - Civilian', 'Non-Lethal Weapons', 13),
	(1085, 'Orbital - Outpost - Scientific', 'Non-Lethal Weapons', 13),
	(1086, 'Orbital - Outpost - Military', 'Non-Lethal Weapons', 13),
	(1087, 'Orbital - Installation - Security Station', 'Non-Lethal Weapons', 19),
	(1088, 'Orbital - Installation - Government', 'Non-Lethal Weapons', 13),
	(1089, 'Surface - Planetary Port - Outpost Civilian', 'Non-Lethal Weapons', 34),
	(1090, 'Surface - Planetary Port - Outpost Industrial', 'Non-Lethal Weapons', 34),
	(1091, 'Surface - Planetary Port - Outpost Scientific', 'Non-Lethal Weapons', 34),
	(1092, 'Surface - Planetary Port - Port', 'Non-Lethal Weapons', 136),
	(1093, 'Orbital - Installation - Pirate Base', 'Reactive Armour', 23),
	(1094, 'Orbital - Installation - Military', 'Reactive Armour', 30),
	(1095, 'Surface - Settlement - Military T1 S', 'Reactive Armour', 24),
	(1096, 'Surface - Settlement - Military T1 M', 'Reactive Armour', 48),
	(1097, 'Surface - Settlement - Military T2 L', 'Reactive Armour', 72),
	(1098, 'Surface - Hub - Military', 'Reactive Armour', 42);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
